FROM python:3.11

COPY requirements.txt app/requirements.txt
WORKDIR /app

RUN pip install -r requirements.txt
COPY . .

RUN ls -lah

EXPOSE 8501
EXPOSE 8100

ENTRYPOINT ["streamlit","run"]

CMD ["home.py"]